/**
 * Generated by: ScrapeOps AI Scraper Generator on 2026-02-16
 * Signup For Free Beta: https://scrapeops.io/app/register/ai-scraper-generator
 * Docs & Updates: https://scrapeops.io/docs/ai-scraper-generator
 * For Support & Feedback Email: ai-scraper-generator@scrapeops.io
 */

const { chromium } = require('playwright-extra');
const StealthPlugin = require('puppeteer-extra-plugin-stealth');
const cheerio = require('cheerio');
const fs = require('fs');
const { promisify } = require('util');

// Add stealth plugin
chromium.use(StealthPlugin());

const API_KEY = 'YOUR-API_KEY';

/**
 * Generate output filename with current timestamp
 * @returns {string} Output filename
 */
function generateOutputFilename() {
    const now = new Date();
    const timestamp = now.getFullYear().toString() +
        (now.getMonth() + 1).toString().padStart(2, '0') +
        now.getDate().toString().padStart(2, '0') + '_' +
        now.getHours().toString().padStart(2, '0') +
        now.getMinutes().toString().padStart(2, '0') +
        now.getSeconds().toString().padStart(2, '0');
    return 'beautylish_com_product_category_page_scraper_data_' + timestamp + '.jsonl';
}

// ScrapeOps Residential Proxy Configuration
const PROXY_CONFIG = {
    server: 'http://residential-proxy.scrapeops.io:8181',
    username: 'scrapeops',
    password: API_KEY
};

// Configuration
const CONFIG = {
    maxRetries: 3,
    maxConcurrency: 1,
    timeout: 180000,
    outputFile: generateOutputFilename()
};

/**
 * Data pipeline for handling scraped data
 */
class DataPipeline {
    constructor(outputFile = CONFIG.outputFile) {
        this.itemsSeen = new Set();
        this.outputFile = outputFile;
        this.writeFile = promisify(fs.appendFile);
    }

    isDuplicate(data) {
        const itemKey = JSON.stringify(data);
        if (this.itemsSeen.has(itemKey)) {
            console.warn('Duplicate item found, skipping');
            return true;
        }
        this.itemsSeen.add(itemKey);
        return false;
    }

    async addData(scrapedData) {
        if (!this.isDuplicate(scrapedData)) {
            try {
                const jsonLine = JSON.stringify(scrapedData) + '\n';
                await this.writeFile(this.outputFile, jsonLine, 'utf8');
                console.log('Saved item to', this.outputFile);
            } catch (error) {
                console.error('Error saving data:', error);
            }
        }
    }
}

/**
 * Utility to make URLs absolute
 * @param {string} urlStr 
 * @returns {string}
 */
function makeAbsoluteURL(urlStr) {
    if (!urlStr) return "";
    if (urlStr.startsWith("http://") || urlStr.startsWith("https://")) return urlStr;
    if (urlStr.startsWith("//")) return "https:" + urlStr;
    const domain = "https://www.beautylish.com";
    if (urlStr.startsWith("/")) return domain + urlStr;
    return domain + "/" + urlStr;
}

/**
 * Strip HTML tags from string
 * @param {string} htmlContent 
 * @returns {string}
 */
function stripHTML(htmlContent) {
    if (!htmlContent) return "";
    return htmlContent.replace(/<[^>]*>/g, ' ').trim();
}

/**
 * Parse numeric price from string
 * @param {string} priceText 
 * @returns {number}
 */
function parseNumericPrice(priceText) {
    if (!priceText) return 0.0;
    const cleanText = priceText.toString().replace(/,/g, '');
    const match = cleanText.match(/[\d,]+\.?\d*/);
    return match ? parseFloat(match[0]) : 0.0;
}

/**
 * Convert interface generic to string (Helper for Go port)
 * @param {any} val 
 * @returns {string}
 */
function interfaceToString(val) {
    if (val === null || val === undefined) return "";
    return val.toString();
}

/**
 * Extract structured data from HTML using Cheerio
 * @param {Object} $ - Cheerio instance
 * @param {string} url - Source URL
 * @returns {Object|null} - Extracted data or null
 */
function extractData($, url) {
    try {
        const outputData = {
            url: url,
            timestamp: new Date().toISOString(),
            appliedFilters: [],
            bannerImage: null,
            breadcrumbs: null,
            categoryId: "",
            categoryName: "",
            categoryUrl: "",
            description: null,
            pagination: null,
            products: [],
            subcategories: []
        };

        // Applied Filters from Canonical Link
        const canonical = $("link[rel='canonical']").attr("href");
        if (canonical) {
            outputData.categoryUrl = makeAbsoluteURL(canonical);
            if (canonical.includes("tag=")) {
                let filterVal = canonical.split("tag=")[1] || "";
                if (filterVal.includes("&")) {
                    filterVal = filterVal.split("&")[0];
                }
                outputData.appliedFilters.push({
                    filterName: "tag",
                    filterValue: filterVal
                });
                outputData.categoryId = filterVal;
            }
        }

        // Category Name from Title
        const titleText = $("title").first().text();
        if (titleText.includes("|")) {
            outputData.categoryName = titleText.split("|")[0].trim();
        }

        // Subcategories
        $(".squeezeBox_item").each((i, el) => {
            const link = $(el).find("a").first();
            const name = link.text().trim();
            const href = link.attr("href");

            if (name && href && name !== "Brands") {
                outputData.subcategories.push({
                    name: name,
                    productCount: null,
                    url: makeAbsoluteURL(href)
                });
            }
        });

        // Product Parsing (JSON-LD)
        let productJson = null;
        $("script[type='application/ld+json']").each((i, el) => {
            try {
                const data = JSON.parse($(el).html());
                if (data["@type"] === "Product") {
                    productJson = data;
                }
            } catch (e) {}
        });

        if (productJson) {
            const product = {};

            // Aggregate Rating
            const agg = productJson.aggregateRating || {};
            product.aggregateRating = {
                bestRating: parseNumericPrice(interfaceToString(agg.bestRating)),
                ratingValue: parseNumericPrice(interfaceToString(agg.ratingValue)),
                reviewCount: parseNumericPrice(interfaceToString(agg.reviewCount)),
                worstRating: parseNumericPrice(interfaceToString(agg.worstRating))
            };

            // Availability
            const offer = productJson.offers || {};
            let avail = "in_stock";
            if (offer.availability && interfaceToString(offer.availability).includes("OutOfStock")) {
                avail = "out_of_stock";
            }
            product.availability = avail;

            product.brand = interfaceToString(productJson.brand);
            product.category = interfaceToString(productJson.category);
            product.currency = interfaceToString(offer.priceCurrency) || "USD";
            product.description = stripHTML(interfaceToString(productJson.description));
            product.features = [];

            const imgs = [];
            const rawImgs = Array.isArray(productJson.image) ? productJson.image : (productJson.image ? [productJson.image] : []);
            rawImgs.forEach(img => {
                imgs.push({ altText: "", url: makeAbsoluteURL(interfaceToString(img)) });
            });
            product.images = imgs;

            product.name = interfaceToString(productJson.name);
            product.preDiscountPrice = null;
            product.price = parseNumericPrice(interfaceToString(offer.price));
            product.productId = interfaceToString(productJson.sku);
            product.reviews = [];

            product.seller = {
                name: "Beautylish",
                rating: null,
                url: "https://www.beautylish.com"
            };

            product.serialNumbers = [];
            product.specifications = [];
            product.url = outputData.categoryUrl;
            product.videos = [];

            outputData.products.push(product);
        }

        return outputData;
    } catch (error) {
        console.error('Error extracting data from', url, ':', error);
        return null;
    }
}

/**
 * Scrape a single page with retry logic using Playwright with stealth
 * @param {string} url - URL to scrape
 * @param {DataPipeline} pipeline - Data pipeline instance
 * @param {Object} browser - Playwright browser instance
 * @param {number} retries - Number of retries
 */
async function scrapePage(url, pipeline, browser, retries = CONFIG.maxRetries) {
    let success = false;
    let attempts = 0;

    while (attempts <= retries && !success) {
        let context = null;
        let page = null;
        
        try {
            context = await browser.newContext({
                ignoreHTTPSErrors: true,
                viewport: { width: 1920, height: 1080 },
                userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36'
            });
            
            page = await context.newPage();
            
            await page.route('**/*', (route) => {
                const resourceType = route.request().resourceType();
                if (['image', 'media', 'font', 'stylesheet'].includes(resourceType)) {
                    route.abort();
                } else {
                    route.continue();
                }
            });
            
            await page.goto(url, { 
                waitUntil: 'domcontentloaded',
                timeout: CONFIG.timeout 
            });
            
            await page.waitForTimeout(1000);
            
            const bodyHTML = await page.evaluate(() => document.body.innerHTML);
            const $ = cheerio.load(bodyHTML);
            
            const scrapedData = extractData($, url);
            
            if (scrapedData) {
                await pipeline.addData(scrapedData);
                success = true;
                console.log('Successfully scraped:', url);
            } else {
                console.warn('No data extracted from:', url);
            }
        } catch (error) {
            console.error('Exception scraping', url, ':', error.message);
            
            if (attempts < retries) {
                const delay = Math.pow(2, attempts) * 1000;
                console.log('Retrying in', delay, 'ms...');
                await new Promise(resolve => setTimeout(resolve, delay));
            }
        } finally {
            if (page) await page.close();
            if (context) await context.close();
            attempts++;
        }
    }

    if (!success) {
        console.error('Failed to scrape', url, 'after', retries, 'retries');
    }
}

/**
 * Scrape multiple URLs concurrently with controlled concurrency
 * @param {string[]} urls - Array of URLs to scrape
 */
async function concurrentScraping(urls) {
    const pipeline = new DataPipeline(CONFIG.outputFile);
    
    const browser = await chromium.launch({
        headless: true,
        proxy: PROXY_CONFIG,
        args: [
            '--no-sandbox',
            '--disable-setuid-sandbox',
            '--disable-dev-shm-usage',
            '--disable-accelerated-2d-canvas',
            '--no-first-run',
            '--no-zygote',
            '--disable-gpu',
            '--disable-web-security'
        ]
    });

    try {
        for (let i = 0; i < urls.length; i += CONFIG.maxConcurrency) {
            const batch = urls.slice(i, i + CONFIG.maxConcurrency);
            const promises = batch.map(url => scrapePage(url, pipeline, browser, CONFIG.maxRetries));
            
            try {
                await Promise.all(promises);
                console.log('Completed batch', Math.floor(i / CONFIG.maxConcurrency) + 1, 'of', Math.ceil(urls.length / CONFIG.maxConcurrency));
            } catch (error) {
                console.error('Error in batch processing:', error);
            }
        }
    } finally {
        await browser.close();
    }
}

/**
 * Main execution function
 */
async function main() {
    const urls = [
        'https://www.beautylish.com/shop/browse?tag=skincare',
    ];

    console.log('Starting concurrent scraping with NodeJS Playwright-Extra + Stealth...');
    console.log('URLs to scrape:', urls.length);
    console.log('Max concurrency:', CONFIG.maxConcurrency);
    console.log('Output file:', CONFIG.outputFile);

    try {
        await concurrentScraping(urls);
        console.log('Scraping completed successfully!');
    } catch (error) {
        console.error('Scraping failed:', error);
        process.exit(1);
    }
}

if (require.main === module) {
    main().catch(console.error);
}

module.exports = { extractData, scrapePage, concurrentScraping, DataPipeline };