/**
 * Generated by: ScrapeOps AI Scraper Generator on 2026-02-16
 * Signup For Free Beta: https://scrapeops.io/app/register/ai-scraper-generator
 * Docs & Updates: https://scrapeops.io/docs/ai-scraper-generator
 * For Support & Feedback Email: ai-scraper-generator@scrapeops.io
 */

const axios = require('axios');
const cheerio = require('cheerio');
const fs = require('fs');
const { promisify } = require('util');

const API_KEY = 'YOUR-API_KEY';

/**
 * Generate output filename with current timestamp
 * @returns {string} Output filename
 */
function generateOutputFilename() {
    const now = new Date();
    const timestamp = now.getFullYear().toString() +
        (now.getMonth() + 1).toString().padStart(2, '0') +
        now.getDate().toString().padStart(2, '0') + '_' +
        now.getHours().toString().padStart(2, '0') +
        now.getMinutes().toString().padStart(2, '0') +
        now.getSeconds().toString().padStart(2, '0');
    return 'beautylish_com_product_category_page_scraper_data_' + timestamp + '.jsonl';
}

// Configuration
const CONFIG = {
    maxRetries: 3,
    maxConcurrency: 1,
    timeout: 30000,
    outputFile: generateOutputFilename()
};

/**
 * Data pipeline for handling scraped data
 */
class DataPipeline {
    constructor(outputFile = CONFIG.outputFile) {
        this.itemsSeen = new Set();
        this.outputFile = outputFile;
        this.writeFile = promisify(fs.appendFile);
    }

    /**
     * Check if item is duplicate based on unique identifier
     * @param {Object} data - Scraped data object
     * @returns {boolean} - True if duplicate
     */
    isDuplicate(data) {
        const itemKey = JSON.stringify(data);
        if (this.itemsSeen.has(itemKey)) {
            console.warn('Duplicate item found, skipping:', itemKey.substring(0, 100));
            return true;
        }
        this.itemsSeen.add(itemKey);
        return false;
    }

    /**
     * Add scraped data to output file
     * @param {Object} scrapedData - Data to save
     */
    async addData(scrapedData) {
        if (!this.isDuplicate(scrapedData)) {
            try {
                const jsonLine = JSON.stringify(scrapedData) + '\n';
                await this.writeFile(this.outputFile, jsonLine, 'utf8');
                console.log('Saved item to', this.outputFile);
            } catch (error) {
                console.error('Error saving data:', error);
            }
        }
    }
}

/**
 * Helper to strip HTML tags
 * @param {string} html 
 * @returns {string}
 */
function stripHTML(html) {
    if (!html) return "";
    return html.replace(/<[^>]*>/g, ' ').trim();
}

/**
 * Detect currency from price string
 * @param {string} priceText 
 * @returns {string}
 */
function detectCurrency(priceText) {
    const text = priceText.toUpperCase();
    const currencyMap = {
        "USD": "USD", "US$": "USD", "US $": "USD", "$": "USD",
        "EUR": "EUR", "€": "EUR",
        "GBP": "GBP", "£": "GBP", "GB£": "GBP",
        "JPY": "JPY", "¥": "JPY", "JP¥": "JPY",
        "CAD": "CAD", "CA$": "CAD", "C$": "CAD",
        "AUD": "AUD", "AU$": "AUD", "A$": "AUD",
        "CNY": "CNY", "CN¥": "CNY", "RMB": "CNY",
        "CHF": "CHF", "FR.": "CHF",
        "SEK": "SEK", "KR": "SEK",
        "NZD": "NZD", "NZ$": "NZD",
    };
    for (const [code, currency] of Object.entries(currencyMap)) {
        if (text.includes(code)) return currency;
    }
    return "USD";
}

/**
 * Standardize URLs to absolute
 * @param {string} urlStr 
 * @returns {string}
 */
function makeAbsoluteURL(urlStr) {
    if (!urlStr) return "";
    if (urlStr.startsWith("http://") || urlStr.startsWith("https://")) return urlStr;
    if (urlStr.startsWith("//")) return "https:" + urlStr;
    const domain = "https://www.beautylish.com";
    if (urlStr.startsWith("/")) return domain + urlStr;
    return domain + "/" + urlStr;
}

/**
 * Extract structured data from HTML using Cheerio
 * @param {Object} $ - Cheerio instance
 * @param {string} url - Source URL
 * @returns {Object|null} - Extracted data or null
 */
function extractData($, url) {
    try {
        const outputData = {};
        
        // Extract Applied Filters
        let appliedFilters = [];
        let filterTag = "";
        const canonical = $("link[rel='canonical']").attr("href") || "";
        if (canonical.includes("tag=")) {
            const parts = canonical.split("tag=");
            if (parts.length > 1) {
                filterTag = parts[1];
                appliedFilters.push({
                    filterName: "tag",
                    filterValue: filterTag
                });
            }
        }
        outputData.appliedFilters = appliedFilters;
        outputData.bannerImage = null;
        outputData.breadcrumbs = null;
        outputData.categoryId = filterTag;

        // Category Name from Title
        let categoryName = "";
        const titleText = $("title").text();
        if (titleText.includes("|")) {
            categoryName = titleText.split("|")[0].trim();
        }
        outputData.categoryName = categoryName;
        outputData.categoryUrl = makeAbsoluteURL(canonical);
        outputData.description = null;
        outputData.pagination = null;

        let products = [];

        // Primary Strategy: DOM Selection
        const items = $(".product-list-item, .product-grid-item, .product-grid .item, [itemtype='http://schema.org/Product'], .item-container, .grid-item, [data-testid='product-card'], .product-card, .product-item");
        
        items.each((i, el) => {
            const s = $(el);
            const product = {};

            // Brand
            product.brand = s.find(".product-brand, [itemprop='brand'], .brand, .manufacturer, .product-card__brand, .brand-name").first().text().trim();
            
            // Name
            product.name = s.find(".product-name, [itemprop='name'], .name, .title, .product-card__name, .product-title").first().text().trim();

            // URL
            let href = s.find("a[href*='/s/'], a[href*='/p/']").first().attr("href") || s.find("a").first().attr("href");
            product.url = makeAbsoluteURL(href);

            // Image
            const img = s.find("img").first();
            let imageUrl = img.attr("data-thumbnail-src") || img.attr("data-src") || img.attr("data-original");
            if (!imageUrl) {
                const src = img.attr("src");
                if (src && !src.includes("data:image")) imageUrl = src;
            }
            product.image = makeAbsoluteURL(imageUrl);

            // Price
            const priceEl = s.find(".product-price, [itemprop='price'], .price, .amount, .price-display, .product-card__price, .price-tag").first();
            const priceText = priceEl.text().trim();
            if (priceText) {
                product.price = priceText;
                product.currency = detectCurrency(priceText);
                const priceMatch = priceText.replace(/,/g, "").match(/[0-9.]+(\.[0-9]+)?/);
                if (priceMatch) {
                    product.priceValue = parseFloat(priceMatch[0]);
                }
            }

            if (product.name || product.url) {
                products.push(product);
            }
        });

        // Fallback Strategy 1: JSON-LD
        if (products.length === 0) {
            $("script[type='application/ld+json']").each((i, el) => {
                try {
                    const data = JSON.parse($(el).text());
                    const processItem = (item) => {
                        const p = {
                            name: item.name || "",
                            url: item.url || "",
                            brand: typeof item.brand === 'object' ? item.brand.name : item.brand
                        };
                        if (p.name) products.push(p);
                    };

                    if (data["@type"] === "ItemList") {
                        (data.itemListElement || []).forEach(el => {
                            if (el.item) processItem(el.item);
                        });
                    } else if (data["@type"] === "Product") {
                        processItem(data);
                    }
                } catch (e) {}
            });
        }

        // Fallback Strategy 2: JS State Variable
        if (products.length === 0) {
            $("script").each((i, el) => {
                const content = $(el).text();
                if (content.includes("window.__INITIAL_STATE__") || content.includes("window.__PRELOADED_STATE__") || content.includes("beautylish.items")) {
                    const jsonMatch = content.match(/\{.*\}/s);
                    if (jsonMatch) {
                        try {
                            const state = JSON.parse(jsonMatch[0]);
                            let items = [];
                            if (state.catalog && state.catalog.products) items = state.catalog.products;
                            else if (state.browse && state.browse.items) items = state.browse.items;
                            else if (Array.isArray(state.results)) items = state.results;

                            items.forEach(item => {
                                const p = {
                                    name: item.product_name || item.name || "",
                                    brand: item.brand_name || item.brand || ""
                                };
                                if (item.slug) p.url = makeAbsoluteURL("/s/" + item.slug);
                                else if (item.url) p.url = makeAbsoluteURL(item.url);

                                if (item.image_url) p.image = makeAbsoluteURL(item.image_url);

                                if (typeof item.price === 'number') {
                                    p.priceValue = item.price;
                                } else if (typeof item.price === 'string') {
                                    const m = item.price.replace(/,/g, "").match(/[0-9.]+(\.[0-9]+)?/);
                                    if (m) p.priceValue = parseFloat(m[0]);
                                }
                                if (p.name) products.push(p);
                            });
                        } catch (e) {}
                    }
                }
            });
        }

        outputData.products = products;

        // Subcategories
        let subcategories = [];
        $(".squeezeBox_sublist .squeezeBox_item").each((i, el) => {
            const s = $(el);
            let link = s.find("a.squeezeBox_link");
            if (link.length === 0) link = s.find("a");
            
            const name = link.text().trim();
            const href = link.attr("href");
            if (name) {
                subcategories.push({
                    name: name,
                    productCount: null,
                    url: makeAbsoluteURL(href)
                });
            }
        });
        outputData.subcategories = subcategories;

        return outputData;
    } catch (error) {
        console.error('Error extracting data from', url, ':', error);
        return null;
    }
}

/**
 * Create axios instance with proper configuration
 */
function createAxiosInstance() {
    return axios.create({
        timeout: CONFIG.timeout,
        headers: {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
        }
    });
}

/**
 * Scrape a single page with retry logic
 * @param {string} url - URL to scrape
 * @param {DataPipeline} pipeline - Data pipeline instance
 * @param {number} retries - Number of retries
 */
async function scrapePage(url, pipeline, retries = CONFIG.maxRetries) {
    const axiosInstance = createAxiosInstance();
    
    const payload = {
        api_key: API_KEY,
        url: url,
        optimize_request: true 
    };

    let success = false;
    let attempts = 0;

    while (attempts <= retries && !success) {
        try {
            const proxyUrl = 'https://proxy.scrapeops.io/v1/?' + new URLSearchParams(payload);
            const response = await axiosInstance.get(proxyUrl);

            if (response.status === 200) {
                const $ = cheerio.load(response.data);
                const scrapedData = extractData($, url);
                
                if (scrapedData) {
                    await pipeline.addData(scrapedData);
                    success = true;
                    console.log('Successfully scraped:', url);
                } else {
                    console.warn('No data extracted from:', url);
                }
            } else {
                console.warn('Request failed for', url, 'with status', response.status);
            }
        } catch (error) {
            console.error('Exception scraping', url, ':', error.message);
            if (attempts < retries) {
                const delay = Math.pow(2, attempts) * 1000;
                console.log('Retrying in', delay, 'ms...');
                await new Promise(resolve => setTimeout(resolve, delay));
            }
        } finally {
            attempts++;
        }
    }

    if (!success) {
        console.error('Failed to scrape', url, 'after', retries, 'retries');
    }
}

/**
 * Scrape multiple URLs concurrently with controlled concurrency
 * @param {string[]} urls - Array of URLs to scrape
 * @param {number} maxConcurrency - Maximum concurrent requests
 * @param {number} maxRetries - Maximum retries per URL
 * @param {string} outputFile - Output file path
 */
async function concurrentScraping(urls, maxConcurrency = CONFIG.maxConcurrency, maxRetries = CONFIG.maxRetries, outputFile = CONFIG.outputFile) {
    const pipeline = new DataPipeline(outputFile);
    
    for (let i = 0; i < urls.length; i += maxConcurrency) {
        const batch = urls.slice(i, i + maxConcurrency);
        const promises = batch.map(url => scrapePage(url, pipeline, maxRetries));
        
        try {
            await Promise.all(promises);
            console.log('Completed batch', Math.floor(i / maxConcurrency) + 1, 'of', Math.ceil(urls.length / maxConcurrency));
        } catch (error) {
            console.error('Error in batch processing:', error);
        }
    }
}

/**
 * Main execution function
 */
async function main() {
    const urls = [
        'https://www.beautylish.com/shop/browse?tag=skincare',
    ];

    console.log('Starting concurrent scraping with NodeJS Cheerio & Axios...');
    console.log('URLs to scrape:', urls.length);
    console.log('Max concurrency:', CONFIG.maxConcurrency);
    console.log('Output file:', CONFIG.outputFile);

    try {
        await concurrentScraping(urls, CONFIG.maxConcurrency, CONFIG.maxRetries, CONFIG.outputFile);
        console.log('Scraping completed successfully!');
    } catch (error) {
        console.error('Scraping failed:', error);
        process.exit(1);
    }
}

if (require.main === module) {
    main().catch(console.error);
}

module.exports = { extractData, scrapePage, concurrentScraping, DataPipeline };