/**
 * Generated by: ScrapeOps AI Scraper Generator on 2026-02-16
 * Signup For Free Beta: https://scrapeops.io/app/register/ai-scraper-generator
 * Docs & Updates: https://scrapeops.io/docs/ai-scraper-generator
 * For Support & Feedback Email: ai-scraper-generator@scrapeops.io
 */

const puppeteer = require('puppeteer-extra');
const StealthPlugin = require('puppeteer-extra-plugin-stealth');
const cheerio = require('cheerio');
const fs = require('fs');
const { promisify } = require('util');

// Add stealth plugin
puppeteer.use(StealthPlugin());

const API_KEY = 'YOUR-API_KEY';

/**
 * Generate output filename with current timestamp
 * @returns {string} Output filename
 */
function generateOutputFilename() {
    const now = new Date();
    const timestamp = now.getFullYear().toString() +
        (now.getMonth() + 1).toString().padStart(2, '0') +
        now.getDate().toString().padStart(2, '0') + '_' +
        now.getHours().toString().padStart(2, '0') +
        now.getMinutes().toString().padStart(2, '0') +
        now.getSeconds().toString().padStart(2, '0');
    return 'beautylish_com_product_search_page_scraper_data_' + timestamp + '.jsonl';
}

// ScrapeOps Residential Proxy Configuration
const PROXY_SERVER = 'residential-proxy.scrapeops.io';
const PROXY_PORT = '8181';
const PROXY_USERNAME = 'scrapeops';
const PROXY_PASSWORD = API_KEY;

// Configuration
const CONFIG = {
    maxRetries: 3,
    maxConcurrency: 1,
    timeout: 180000,
    outputFile: generateOutputFilename()
};

/**
 * Data pipeline for handling scraped data
 */
class DataPipeline {
    constructor(outputFile = CONFIG.outputFile) {
        this.itemsSeen = new Set();
        this.outputFile = outputFile;
        this.writeFile = promisify(fs.appendFile);
    }

    isDuplicate(data) {
        const itemKey = JSON.stringify(data);
        if (this.itemsSeen.has(itemKey)) {
            console.warn('Duplicate item found, skipping');
            return true;
        }
        this.itemsSeen.add(itemKey);
        return false;
    }

    async addData(scrapedData) {
        if (!this.isDuplicate(scrapedData)) {
            try {
                const jsonLine = JSON.stringify(scrapedData) + '\n';
                await this.writeFile(this.outputFile, jsonLine, 'utf8');
                console.log('Saved item to', this.outputFile);
            } catch (error) {
                console.error('Error saving data:', error);
            }
        }
    }
}

/**
 * Extract structured data from HTML using Cheerio
 * @param {Object} $ - Cheerio instance
 * @param {string} url - Source URL
 * @returns {Object|null} - Extracted data or null
 */
function extractData($, url) {
    try {
        const makeAbsoluteURL = (urlStr) => {
            if (!urlStr) return "";
            if (urlStr.startsWith("http://") || urlStr.startsWith("https://")) return urlStr;
            if (urlStr.startsWith("//")) return "https:" + urlStr;
            const domain = "https://www.beautylish.com";
            if (urlStr.startsWith("/")) return domain + urlStr;
            return domain + "/" + urlStr;
        };

        const detectCurrency = (priceText) => {
            priceText = priceText.toUpperCase();
            const currencyMap = {
                "USD": "USD", "US$": "USD", "US $": "USD", "$": "USD",
                "EUR": "EUR", "€": "EUR",
                "GBP": "GBP", "£": "GBP", "GB£": "GBP",
                "JPY": "JPY", "¥": "JPY", "JP¥": "JPY",
                "CAD": "CAD", "CA$": "CAD", "C$": "CAD",
                "AUD": "AUD", "AU$": "AUD", "A$": "AUD",
                "CNY": "CNY", "CN¥": "CNY", "RMB": "CNY",
                "CHF": "CHF", "FR.": "CHF",
                "SEK": "SEK", "KR": "SEK",
                "NZD": "NZD", "NZ$": "NZD",
            };
            for (const [code, currency] of Object.entries(currencyMap)) {
                if (priceText.includes(code)) return currency;
            }
            return "USD";
        };

        const extractNumericPrice = (priceText) => {
            const cleanText = priceText.replace(/,/g, '');
            const match = cleanText.match(/([\d,]+\.?\d*)/);
            if (match) {
                return parseFloat(match[1]);
            }
            return 0.0;
        };

        const outputData = {
            breadcrumbs: [],
            pagination: null,
            products: [],
            recommendations: null,
            relatedSearches: null,
            searchMetadata: {},
            sponsoredProducts: null,
            timestamp: new Date().toISOString(),
            source_url: url
        };

        // Primary Strategy: CSS Selectors
        const selector = "#product-grid .product, .products-list .product-item, [itemtype='http://schema.org/Product'], .product-grid-item, .search-result, .product-list > div, .search-results-container [data-product-id], .product-card, .grid-item";
        
        $(selector).each((i, el) => {
            const s = $(el);
            const product = {};
            
            // Extract Name
            const name = s.find(".product-name, [itemprop='name'], .name, h3, h4, .title, .product-title, .card-title, .item-name").first().text().trim();
            product.name = name;
            
            // Extract Brand
            const brand = s.find(".product-brand, [itemprop='brand'], .brand, .vendor, .brand-name, .card-vendor, .item-brand").first().text().trim();
            product.brand = brand;
            
            // Extract URL
            const href = s.find("a[href]").first().attr("href");
            if (href) {
                product.url = makeAbsoluteURL(href);
            }
            
            // Extract Image
            const img = s.find("img").first();
            const src = img.attr("src") || img.attr("data-src") || img.attr("data-original");
            if (src) {
                product.imageUrl = makeAbsoluteURL(src);
            }
            
            // Extract Price
            const priceElem = s.find(".product-price, [itemprop='price'], .price, .amount, .current-price, .price-display, .card-price, .item-price").first();
            let priceText = priceElem.text().trim();
            if (!priceText) {
                priceText = priceElem.attr("content") || "";
            }
            
            if (priceText) {
                product.price = extractNumericPrice(priceText);
                product.currency = detectCurrency(priceText);
            }
            
            if (name) {
                outputData.products.push(product);
            }
        });

        // Fallback Strategy 1: JSON-LD
        if (outputData.products.length === 0) {
            $("script[type='application/ld+json']").each((i, el) => {
                try {
                    const data = JSON.parse($(el).html());
                    if (data["@type"] === "ItemList" && data.itemListElement) {
                        data.itemListElement.forEach(item => {
                            const itemData = item.item || (item["@type"] === "Product" ? item : null);
                            if (itemData) {
                                outputData.products.push({
                                    name: itemData.name,
                                    brand: itemData.brand,
                                    url: itemData.url ? makeAbsoluteURL(itemData.url) : ""
                                });
                            }
                        });
                    }
                } catch (e) {}
            });
        }

        // Fallback Strategy 2: Javascript Variable Extraction
        if (outputData.products.length === 0) {
            const htmlContent = $.html();
            
            // Try standard "products" array
            const productsRegex = /"products"\s*:\s*(\[.*?\])/s;
            const prodMatches = htmlContent.match(productsRegex);
            if (prodMatches && prodMatches[1]) {
                try {
                    const rawProds = JSON.parse(prodMatches[1]);
                    rawProds.forEach(rp => {
                        outputData.products.push({
                            name: rp.name,
                            brand: rp.brand_name,
                            url: rp.id ? makeAbsoluteURL("/s/" + rp.id) : ""
                        });
                    });
                } catch (e) {}
            }

            // Try INITIAL_STATE
            if (outputData.products.length === 0) {
                const stateRegex = /window\.__INITIAL_STATE__\s*=\s*({.*?});/s;
                const stateMatches = htmlContent.match(stateRegex);
                if (stateMatches && stateMatches[1]) {
                    try {
                        const state = JSON.parse(stateMatches[1]);
                        const results = state?.search?.results;
                        if (Array.isArray(results)) {
                            results.forEach(res => {
                                outputData.products.push({
                                    name: res.name,
                                    brand: res.brand_name,
                                    url: res.slug ? makeAbsoluteURL("/s/" + res.slug) : ""
                                });
                            });
                        }
                    } catch (e) {}
                }
            }
        }

        // Search Metadata
        const metaQuery = $(".search-metadata").first();
        let query = metaQuery.attr("data-query") || $("input.ocnSearch_input").first().val() || "";
        
        let searchUrl = metaQuery.attr("data-search-url") || $("link[rel='canonical']").first().attr("href") || "";
        if (searchUrl && !searchUrl.startsWith("http")) {
            searchUrl = makeAbsoluteURL(searchUrl);
        }

        outputData.searchMetadata = {
            query: query,
            resultsDisplayed: outputData.products.length,
            searchType: "keyword",
            searchUrl: searchUrl,
            totalResults: outputData.products.length
        };

        return outputData;
    } catch (error) {
        console.error('Error extracting data from', url, ':', error);
        return null;
    }
}

/**
 * Scrape a single page with retry logic using Puppeteer with stealth
 */
async function scrapePage(url, pipeline, browser, retries = CONFIG.maxRetries) {
    let success = false;
    let attempts = 0;

    while (attempts <= retries && !success) {
        let page = null;
        
        try {
            page = await browser.newPage();
            await page.setViewport({ width: 1920, height: 1080 });
            await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36');
            
            await page.setRequestInterception(true);
            page.on('request', (request) => {
                const resourceType = request.resourceType();
                if (['image', 'media', 'font', 'stylesheet'].includes(resourceType)) {
                    request.abort();
                } else {
                    request.continue();
                }
            });
            
            await page.authenticate({
                username: PROXY_USERNAME,
                password: PROXY_PASSWORD
            });
            
            await page.goto(url, { 
                waitUntil: 'networkidle2',
                timeout: CONFIG.timeout 
            });
            
            // Wait for product grid or dynamic content
            try {
                await page.waitForSelector('#product-grid, .products-list, .search-result', { timeout: 10000 });
            } catch (e) {
                console.log("Specific selector not found, proceeding with body scan");
            }
            
            const bodyHTML = await page.evaluate(() => document.body.innerHTML);
            const $ = cheerio.load(bodyHTML);
            
            const scrapedData = extractData($, url);
            
            if (scrapedData && scrapedData.products && scrapedData.products.length > 0) {
                await pipeline.addData(scrapedData);
                success = true;
                console.log('Successfully scraped:', url);
            } else {
                console.warn('No products extracted from:', url);
                // Even if no products, we might want metadata
                if (scrapedData) {
                    await pipeline.addData(scrapedData);
                    success = true;
                }
            }
        } catch (error) {
            console.error('Exception scraping', url, ':', error.message);
            if (attempts < retries) {
                const delay = Math.pow(2, attempts) * 1000;
                console.log('Retrying in', delay, 'ms...');
                await new Promise(resolve => setTimeout(resolve, delay));
            }
        } finally {
            if (page) await page.close();
            attempts++;
        }
    }

    if (!success) {
        console.error('Failed to scrape', url, 'after', retries, 'retries');
    }
}

/**
 * Scrape multiple URLs concurrently
 */
async function concurrentScraping(urls) {
    const pipeline = new DataPipeline(CONFIG.outputFile);
    
    const browser = await puppeteer.launch({
        headless: 'new',
        ignoreHTTPSErrors: true,
        args: [
            `--proxy-server=http://${PROXY_SERVER}:${PROXY_PORT}`,
            '--no-sandbox',
            '--disable-setuid-sandbox',
            '--disable-dev-shm-usage',
            '--disable-accelerated-2d-canvas',
            '--no-first-run',
            '--no-zygote',
            '--disable-gpu',
            '--disable-web-security'
        ]
    });

    try {
        for (let i = 0; i < urls.length; i += CONFIG.maxConcurrency) {
            const batch = urls.slice(i, i + CONFIG.maxConcurrency);
            const promises = batch.map(url => scrapePage(url, pipeline, browser, CONFIG.maxRetries));
            
            try {
                await Promise.all(promises);
                console.log('Completed batch', Math.floor(i / CONFIG.maxConcurrency) + 1, 'of', Math.ceil(urls.length / CONFIG.maxConcurrency));
            } catch (error) {
                console.error('Error in batch processing:', error);
            }
        }
    } finally {
        await browser.close();
    }
}

/**
 * Main execution function
 */
async function main() {
    const urls = [
        'https://www.beautylish.com/shop/browse?utm_source=internal_search&utm_campaign=Search+Beautylish+Products&q=hair+shampoo',
    ];

    console.log('Starting concurrent scraping with NodeJS Puppeteer-Extra + Stealth...');
    console.log('URLs to scrape:', urls.length);
    console.log('Max concurrency:', CONFIG.maxConcurrency);
    console.log('Output file:', CONFIG.outputFile);

    try {
        await concurrentScraping(urls);
        console.log('Scraping completed successfully!');
    } catch (error) {
        console.error('Scraping failed:', error);
        process.exit(1);
    }
}

if (require.main === module) {
    main().catch(console.error);
}

module.exports = { extractData, scrapePage, concurrentScraping, DataPipeline };